### ISSUE TITLE
Wrong image is being picked

### ISSUE THREAD

**Issue by khanimdad** [metainspector/metainspector#195]
Trying to get detail from link https://www.quora.com/What-were-the-experiments-conducted-that-would-have-ended-the-world/answer/Bryan-Phelps-3?srid=iM81

But its returning wrong image while it has better image on detail page

**Comment by jaimeiniesta** [comment]
Thanks for the report - can you add what MetaInspector version are you using, what image is picking and which one should pick instead?

**Comment by khanimdad** [comment]
Am using metainspector (4.7.2)

And am getting placeholder image instead of actual image.

FYI: there is no open graph tag on the said page.

**Comment by jaimeiniesta** [comment]
Could you please try with the latest version, 5.3.1 and in case it also fails with this version, let me know the expected URL and the actual URL that it's returning?

**Comment by khanimdad** [comment]
Updated to 5.3.1 but not luck,
page.images.best it returns https://qsf.ec.quoracdn.net/-3-images.placeholder_img.pngb25e022d8984a59c.png

While it should return - https://qph.ec.quoracdn.net/main-qimg-2ea76ac91ba6ec4d48dd3bdf420df58f-c?convert_to_webp=true

**Comment by danielbonnell** [comment]
I'm also encountering this problem quite frequently. I'm running v5.4.0. For example, if I scrape `cnn.com`, both `page.images.first` and `page.images.best` return `http://i.cdn.cnn.com/cnn/.e1mo/img/4.0/logos/menu_entertainment.png`, which is incorrect. The url should be the CNN logo, which in fact does appear in `page.images`, but is near the end of the array. I've tried toggling on/off the `download_images` setting and also calling `page.images.with_size`, but it makes no difference.

**Comment by jaimeiniesta** [comment]
Thanks @danielbonnell and @khanimdad - we need to fix this.

Pull requests are warmly welcomed :)

**Comment by jaimeiniesta** [comment]
@khanimdad @danielbonnell we've just released version 5.4.1, that upgrades gem dependencies and includes support for base64 images, please try again with this version and let me know if this is still an issue.

**Comment by danielbonnell** [comment]
@jaimeiniesta I'm attempting to update now to test the difference but not having much luck. Getting a [strange dependency error](https://stackoverflow.com/questions/42427352/bundler-could-not-find-compatible-versions-for-gem-faraday) from `bundler` that I can't quite wrap my head around.

**Comment by jaimeiniesta** [comment]
@danielbonell I think the problem is with the dependency on instagram-continued, `faraday (~> 0.9.2)` will let you install 0.9.3, 0.9.4, etc., but no 0.10.x or 0.11.x - and metainspector requires now 0.11.x

So I would ask the authors of instagram-continued to relax / upgrade this dependency.

**Comment by danielbonnell** [comment]
@jaimeiniesta I just upgraded to `5.4.1` and this doesn't seem to have improved. With my `cnn.com` example, it's still selecting the wrong image.

**Comment by jaimeiniesta** [comment]
Thanks for the update @danielbonnell - I will take a look as soon as I can. PRs are still welcome :)

**Comment by dhruvbhatia** [comment]
This also happens with pages on the Play Store (`page.images.best` returns the wrong image).
See [example here](https://metainspectordemo.herokuapp.com/scrape?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fhl%3Den%26id%3Dcom.creativetrends.simple.app.pro).

**Comment by jaimeiniesta** [comment]
Thanks, we'll take a look.

Can you please provide exact details:

* MetaInspector and Ruby version being used.
* URL being scraped.
* Expected URL for the image.
* Actual URL for the image.
