### ISSUE TITLE
undefined method `headers' for nil:NilClass

### ISSUE THREAD

**Issue by priyaIntrohive** [metainspector/metainspector#250]
Getting following error in Production environment alone. Tried to reproduce the same in development environment but no luck.

**Error:**
undefined method `headers' for nil:NilClass

**Code:**
```
MetaInspector.new("<some_url>", :connection_timeout => 5, :read_timeout => 5)
```

**Error Trace:**

bundler/gems/metainspector-dd8336538164/lib/meta_inspector/request.rb:50:in `content_type': undefined method `headers' for nil:NilClass (NoMethodError)

from bundler/gems/metainspector-dd8336538164/lib/meta_inspector/document.rb:107:in `document'

from bundler/gems/metainspector-dd8336538164/lib/meta_inspector/document.rb:83:in `to_s'

from bundler/gems/metainspector-dd8336538164/lib/meta_inspector/parser.rb:33:in `parsed'

from bundler/gems/metainspector-dd8336538164/lib/meta_inspector/parser.rb:20:in `initialize'

from bundler/gems/metainspector-dd8336538164/lib/meta_inspector/document.rb:41:in `new'

from bundler/gems/metainspector-dd8336538164/lib/meta_inspector/document.rb:41:in `initialize'

from bundler/gems/metainspector-dd8336538164/lib/meta_inspector.rb:22:in `new'

from bundler/gems/metainspector-dd8336538164/lib/meta_inspector.rb:22:in `new'

**Comment by jaimeiniesta** [comment]
Thanks for the report!

If it's only happening in production, it looks like it may be due to the remote server rejecting the connection from your production IP.

Can you give an example URL so we try to reproduce this?
