### ISSUE TITLE
Metainspector timeout for some sites

### ISSUE THREAD

**Issue by cgarre** [metainspector/metainspector#253]
for example https://www.businesswire.com timesout even on the demo site.

**Comment by jaimeiniesta** [comment]
I don't get a timeout when scraping this site from my development machine:

```
2.3.7 :003 > MetaInspector.new("https://www.businesswire.com/").title
 => "Press release distribution, EDGAR filing, XBRL, regulatory filings | Business Wire"
```

But I do see the timeout on the demo site. This looks like the remote server may be detecting that the request comes from Heroku and blocking it. There's no much that can be done except:

* Setting a higher timeout https://github.com/metainspector/metainspector#timeout--retries
* Try with another User-Agent header https://github.com/metainspector/metainspector#headers
