### ISSUE TITLE
faraday_middleware (0.13.1) is deprecating Faraday::Error::ClientError

### ISSUE THREAD

**Issue by taurusismysign** [metainspector/metainspector#254]
Getting this in logs: 

"NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0"

**Comment by jaimeiniesta** [comment]
Thanks for the warning - I don't find any explicit reference to `Faraday::Error::ClientError` in our code so this seems to be on the `faraday_middleware` dependency itself.

It will disappear once we upgrade to their latest versions - the Faraday team is in process of upgrading its ecosystem, we'll follow along.
