### ISSUE TITLE
twitter.com links not scraped

### ISSUE THREAD

**Issue by cgarre** [metainspector/metainspector#258]
for example 

https://twitter.com/IvankaTrump

doesnt get description , title or images, is this a known issue ?

**Comment by jaimeiniesta** [comment]
What do you get? Please check the response and see if the site is blocking your request.

Where are you making the request from? Do you get the same result if you do the request from your local development server?

**Comment by carsonbaker** [comment]
It doesn't work because Twitter renders the same blank static page for every response and then fills in the content with Ajax.

**Comment by jaimeiniesta** [comment]
@carsonbaker not exactly, what @cgarre complains about is not being able to get the page description, and I'm able to do that from my development server:

```ruby
page.description
 => "Los Tweets más recientes de Ivanka Trump (@IvankaTrump). Wife, mother, sister, daughter. Advisor to POTUS on job creation + economic empowerment, workforce development & entrepreneurship. Personal Pg. Views are my own. Washington, DC"
```

Now, it probably fails in production if Twitter bans the request based on the server IP, for example.

**Comment by carsonbaker** [comment]
```
require 'metainspector'

url = "https://twitter.com/BillGates/status/1213158756915105792"

METAINSPECTOR_OPTIONS_WITH_USER_AGENT = {
  headers: {
    'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36'
  },
}

results_a = MetaInspector.new(url)
results_b = MetaInspector.new(url, METAINSPECTOR_OPTIONS_WITH_USER_AGENT)

puts results_a.best_title == "Bill Gates on Twitter" # outputs true
puts results_b.best_title == "Bill Gates on Twitter" # outputs false
```

Looks like Twitter does different stuff depending on the User-Agent. Obviously this isn't a bug with Metainspector, but I just wanted to give @cgarre an idea of what might be going on, and also make sure I wasn't crazy...

**Comment by jaimeiniesta** [comment]
That's right @carsonbaker , thanks for the example.

Most often, using a custom User-Agent string to fake a browser is the solution. Docs for doing this are here @cgarre 

https://github.com/metainspector/metainspector#headers
