### ISSUE TITLE
Unable to pick favicon

### ISSUE THREAD

**Issue by oyeanuj** [metainspector/metainspector#260]
Hi @jaimeiniesta, not sure if this is known or expected behavior, but I noticed that the favicon icon is not picked consistently by the library.  

For example, for [this Kickstarter url](https://www.kickstarter.com/projects/levelgroundcomics/a-taste-of-home-a-cooking-anthology), the [MetaInspector result](https://metainspectordemo.herokuapp.com/scrape?url=https%3A%2F%2Fwww.kickstarter.com%2Fprojects%2Flevelgroundcomics%2Fa-taste-of-home-a-cooking-anthology) doesn't pick a Favicon even though the page has a favicon.ico file mentioned in the link tag.

Thoughts?

**Comment by jaimeiniesta** [comment]
Thanks for the report, I've verified this fails in MetaInspector 5.9.0

**Comment by oyeanuj** [comment]
If it is helpful, here is what the metascraper JS library is looking for:
 https://github.com/microlinkhq/metascraper/blob/428bb1d37181f384ea68e1bb7919419f2b94ad87/packages/metascraper-logo-favicon/index.js#L35-L38

**Comment by jschwindt** [comment]
Hi @oyeanuj! After some debugging I realized that the site returns a different html from what you get from the browser, and that content doesn’t have a favicon header. I tried different headers and finally found the one that makes it work:

```ruby
headers = { 'accept' => 'text/html' }
url = 'https://www.kickstarter.com/projects/levelgroundcomics/a-taste-of-home-a-cooking-anthology'
p = MetaInspector.new(url, headers: headers)
p.images.favicon
=> "https://a.kickstarter.com/favicon.ico"
```

**Comment by oyeanuj** [comment]
@jschwindt Thanks for digging in! What do you think is the solution for such cases?

It seems like the Favicon rules could be a little bit more robust (like I shared with Metascraper above) as they are able to find it.

**Comment by jschwindt** [comment]
In this particular case the way for the server to respond with the favicon is sending the 'accept' header, and seems to be an easy solution for you to add the header when instantiating the class.

Regarding the Metascraper code, it looks like it was thought to retrieve a logo of the site and not simply the favicon. You can always use xpath on the parsed html, for example:

```ruby
p.parsed.xpath('//link[@rel="apple-touch-icon"]/@href').first.value
```

Anyway you are welcome to send a PR to improve MetaInspector ;-)
