### ISSUE TITLE
Unable to render images that have special characters in src

### ISSUE THREAD

**Issue by kalemi19** [metainspector/metainspector#263]
For example the best image for https://information-mundgesundheit.de/ernaehrungskonzept-zahnarztpraxis/ returns a 404 error: https://information-mundgesundheit.de/wp-content/uploads/2020/05/img-titel-ern%C3%A4hrung-boosting.jpg

The correct src is: https://information-mundgesundheit.de/wp-content/uploads/2020/05/img-titel-ernährung-boosting.jpg (notice the "ä").

I tried unescaping the return src but for some reason the unescaped %C3%A4 (ä) is not the same as the original ä.

Facebook and some other scrapers I tried don't seem to have this problem.

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Finformation-mundgesundheit.de%2Fernaehrungskonzept-zahnarztpraxis%2F

**Comment by jschwindt** [comment]
I've just tried it with version 5.10.0 and it worked fine:

```
irb(main):007:0> m = MetaInspector.new('https://information-mundgesundheit.de/ernaehrungskonzept-zahnarztpraxis/');nil
=> nil
irb(main):008:0> m.images.best
=> "https://information-mundgesundheit.de/wp-content/uploads/2020/05/img-titel-ernährung-boosting.jpg"

~$ wget "https://information-mundgesundheit.de/wp-content/uploads/2020/05/img-titel-ernährung-boosting.jpg"
--2020-05-10 22:07:18--  https://information-mundgesundheit.de/wp-content/uploads/2020/05/img-titel-erna%CC%88hrung-boosting.jpg
Resolving information-mundgesundheit.de (information-mundgesundheit.de)... 85.13.140.228
Connecting to information-mundgesundheit.de (information-mundgesundheit.de)|85.13.140.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 175205 (171K) [image/jpeg]
Saving to: ‘img-titel-ernährung-boosting.jpg’

img-titel-ernährung-boosting.jpg      100%[=======================================================================>] 171.10K   430KB/s    in 0.4s

2020-05-10 22:07:19 (430 KB/s) - ‘img-titel-ernährung-boosting.jpg’ saved [175205/175205]
```
Can you be more specific about how you test it or how you handle the result after getting the image from MetaInspector?

**Comment by kalemi19** [comment]
Maybe the issue has been fixed in 5.10.0. I'm currently using 5.6.0. Let me try it.

Nothing special I'm doing. I'm simply rendering the response as it's done on https://metainspectordemo.herokuapp.com/

As you can see, even on the demo page the best image shows 404 for https://information-mundgesundheit.de/ernaehrungskonzept-zahnarztpraxis/

**Comment by kalemi19** [comment]
I can't upgrade to 5.10.0 due to several dependency conflicts with other gems. I will see if I can do a monkey patch.

**Comment by kalemi19** [comment]
Duplicate of #215 

Avoiding normalizing image URLs seems to be the fix that is already addressed in #215. 

Thanks.

**Comment by jschwindt** [comment]
Indeed 5.10.0 has several dependencies upgrades, but #215 is not new, so you should be able to go back a few versions back.

**Comment by kalemi19** [comment]
True. 5.7.0 does the job. Thanks for the prompt responses.
