### ISSUE TITLE
Metainspector stopped working for twitter.com

### ISSUE THREAD

**Issue by sanattaori** [metainspector/metainspector#265]
Previously metainspector was returning title, description, images for twitter but now it returns nil. 
can you fix this issue?

```
require 'metainspector'

url = "https://twitter.com/narendramodi"

page = MetaInspector.new(url, :allow_non_html_content => true)

puts page.description #output: nil
```
Output for page.meta

`=> {"viewport"=>"width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover", "google-site-verification"=>"V0yIS0Ec_o3Ii9KThrCoMCkwTYMMJ_JYx_RSaGhFYvw", "mobile-web-app-capable"=>"yes", "apple-mobile-web-app-title"=>"Twitter", "apple-mobile-web-app-status-bar-style"=>"white", "theme-color"=>"#ffffff", "origin-trial"=>"Ap6SMBNB0lQoXpXl4I9vyTJqJ7Y0X9tPd6Q6rN697iHdubQQxBcWHy21N3N7uEz7Ba5UKMbN+eLvDczBSbi27AsAAABfeyJvcmlnaW4iOiJodHRwczovL3R3aXR0ZXIuY29tOjQ0MyIsImZlYXR1cmUiOiJCYWRnaW5nIiwiZXhwaXJ5IjoxNTY0NTgyNzY2LCJpc1N1YmRvbWFpbiI6dHJ1ZX0=", "fb:app_id"=>"2231777543", "og:site_name"=>"Twitter", "charset"=>"utf-8"}
`

**Comment by sanattaori** [comment]
Useful meta info removed from twitter.com,
can you add feature to scrape html info like twitter-bio for twitter.com?

**Comment by jschwindt** [comment]
Twitter switched to a full dynamic site (javascript + APIs), there isn’t much we can do to solve that. You should use Twitter's public API.

**Comment by Nakilon** [comment]
Would be cool if the gem told it directly. Like throwing a special exception that the specific website is known to be not parsable. My IRC bot can't obtain the page title.

**Comment by jaimeiniesta** [comment]
Thanks @Nakilon I see your point but I think the exception message should just return the facts, we can't cover every specific case with custom messages.
