### ISSUE TITLE
base_url returns '' 

### ISSUE THREAD

**Issue by ishields** [metainspector/metainspector#266]
Hello! First off, really useful and awesome gem! Great work.

I'm running into an issue with an image not being absolutified.   I tracked it down and believe this occurs because base_url is returning an empty string not the url of the page.  I believe the issue is with this method:
```
def base_url
    base_href || url
end
```
base_href = '' not nil.  As a result the statement returns base_href not url.  

The html the gem is scraping looks weird (maybe invalid?) but still probably worth handling this edge case since it is happening in a common web builder.  

![image](https://user-images.githubusercontent.com/3834864/84270902-68336a00-aaf9-11ea-829a-09405c9c5a4f.png)

PR attached to fix this.

**Comment by jaimeiniesta** [comment]
Thanks for the report! Can you provide an URL that we can test in order to reproduce this?

**Comment by jaimeiniesta** [comment]
Fixed via https://github.com/metainspector/metainspector/pull/267
