### ISSUE TITLE
Error `getaddrinfo: Name or service not known` when scrape page with same host

### ISSUE THREAD

**Issue by blacksyan** [metainspector/metainspector#272]
Currently when I tried to scrape my own website, it return 
```Faraday::ConnectionFailed
Failed to open TCP connection to myweb.co:80 (Connection refused - connect(2) for "myweb.co" port 80)
```

at the beginning I think there is a mistake in my code, but when I tried this link, it raised an error `getaddrinfo: Name or service not known`.

Link to reproduce:
https://metainspectordemo.herokuapp.com/scrape?url=http%3A%2F%2Fhttps%3A%2F%2Fmetainspectordemo.herokuapp.com%2F

**Comment by jschwindt** [comment]
@blacksyan you are trying to scrape an address like this: `http://https://metainspectordemo.herokuapp.com/` that make no sense. Your example with `myweb.co:80` is this:

https://metainspectordemo.herokuapp.com/scrape?url=http%3A%2F%2Fmyweb.co%3A80

and works well.
