### ISSUE TITLE
Different results between local and server

### ISSUE THREAD

**Issue by vnguyen1982** [metainspector/metainspector#283]
Hello,

I have an issue with this result.

It's working well at my local, but when I deploy it to the server, the result is wrong. I can't get page.images.favicon or page.meta.

I checked the result from the server and see different

Attached are the results of my local and server.

[local.txt](https://github.com/metainspector/metainspector/files/6663842/local.txt)
[server.txt](https://github.com/metainspector/metainspector/files/6663843/server.txt)

Please help me, thank you!
Vu

**Comment by jaimeiniesta** [comment]
Hi, the remote server may be responding with different content depending on your IP, that could explain you're getting different results.

Can you share the Ruby code you're using to make those calls so we can reproduce it?

**Comment by jaimeiniesta** [comment]
This is what I get from my dev:

```ruby
➔ irb
irb(main):001:0> require 'metainspector'
=> true
irb(main):002:0> MetaInspector::VERSION
=> "5.11.1"
irb(main):003:0> page = MetaInspector.new("https://www.crainsdetroit.com/sponsored-content/rochester-hills-based-oem-supplier-takes-part-98-2-new-3d-printer")
irb(main):004:0> page.images.favicon
=> "https://s3-prod.crainsdetroit.com/s3fs-public/Icon-Small-50x50%402x_0.png"
irb(main):005:0> page.meta
=> {"robots"=>"noarchive", "twitter:card"=>"summary_large_image", "twitter:description"=>"Initiative encourages small manufacturers to embrace Industry 4.0 technologies.", "twitter:title"=>"Rochester Hills-based OEM supplier takes part from $98 to $2 with new 3D printer", "description"=>"Initiative encourages small manufacturers to embrace Industry 4.0 technologies.", "twitter:url"=>"https://www.crainsdetroit.com/sponsored-content/rochester-hills-based-oem-supplier-takes-part-98-2-new-3d-printer", "twitter:image"=>"https://s3-prod.crainsdetroit.com/styles/800x600/s3/Industry%204.0%20Manufacturing.jpg", "apple-itunes-app"=>"app-id=1551868712", "google-play-app"=>"app-id=com.detroitbusiness.crain", "generator"=>"Drupal 8 (https://www.drupal.org)", "mobileoptimized"=>"width", "handheldfriendly"=>"true", "viewport"=>"width=device-width, initial-scale=1, user-scalable=no", "sailthru.title"=>"Rochester Hills-based OEM supplier takes part from $98 to $2 with new 3D printer", "sailthru.date"=>"2021-06-07T04:00:00-04:00", "sailthru.tags"=>"sponsored-content,manufacturing,business,technology,none", "sailthru.description"=>"Initiative encourages small manufacturers to embrace Industry 4.0 technologies.", "sailthru.author"=>"Crain's Content Studio", "sailthru.image.full"=>"https://s3-prod.crainsdetroit.com/styles/width_792/s3/Industry%204.0%20Manufacturing.jpg", "taxonomy_access_control"=>"None", "taxonomy_category"=>"Sponsored Content", "taxonomy_sponsors"=>"Michigan Economic Development Corporation (MEDC)", "taxonomy_topics"=>"Manufacturing", "published_at"=>"20210607_04:00:00", "year"=>"2021", "article_guid"=>"818356", "url"=>"https://www.crainsdetroit.com/node/818356", "category_name"=>"Sponsored Content", "summary"=>"Initiative encourages small manufacturers to embrace Industry 4.0 technologies.\r\n", "type"=>"Article", "title"=>"Rochester Hills-based OEM supplier takes part from $98 to $2 with new 3D printer", "image"=>"https://s3-prod.crainsdetroit.com/Industry%204.0%20Manufacturing.jpg", "authors"=>"Crain's Content Studio", "og:site_name"=>"Crain's Detroit Business", "og:url"=>"https://www.crainsdetroit.com/sponsored-content/rochester-hills-based-oem-supplier-takes-part-98-2-new-3d-printer", "og:title"=>"Rochester Hills-based OEM supplier takes part from $98 to $2 with new 3D printer", "og:image"=>"https://s3-prod.crainsdetroit.com/styles/800x600/s3/Industry%204.0%20Manufacturing.jpg", "og:image:url"=>"https://s3-prod.crainsdetroit.com/styles/800x600/s3/Industry%204.0%20Manufacturing.jpg", "article:section"=>"Sponsored Content", "article:published_time"=>"2021-06-07T00:00:00-0400", "charset"=>"utf-8"}
```

**Comment by vnguyen1982** [comment]
First, my code is:
`page = MetaInspector.new(params[:url])`

And now is
`page = MetaInspector.new(params[:url],
                                 :connection_timeout => 5, :read_timeout => 5,
                                 :headers => { 'User-Agent' => user_agent, 'Accept-Encoding' => 'identity' },
                                 :faraday_options => { :ssl => { :verify => false } },
                                 :html_content_only => true)`

**Comment by vnguyen1982** [comment]
I tested with many URLs and still have different results

**Comment by vnguyen1982** [comment]
I just tried to test in IRB command on the remote server. Seriously, it's working, can get favicon... but still not work on the website

You can check the result from web API here
https://app.sidepitch.com/api/v1/chats/scrape_website_meta/?url=www.crainsdetroit.com/sponsored-content/rochester-hills-based-oem-supplier-takes-part-98-2-new-3d-printer

**Comment by vnguyen1982** [comment]
Trying in Rails Console on my remote server, crawling URL is https://google.com 
It can't get metadata.

But still working well in IRB or on my local

![Screen Shot 2021-06-16 at 11 19 49 AM](https://user-images.githubusercontent.com/4177595/122272032-f375d700-ce94-11eb-862c-0d300a57a18d.png)

**Comment by vnguyen1982** [comment]
Oh, I know the reason. Something when wrong with my gems version on my remote server. Ok, I fixed it. Thanks so much.
